---
- name: Install EPEL (RedHat)
  package:
    name: "epel-release"
    state: present
  when: ansible_os_family == "Redhat"

- name: Install RPM Fusion Repos (Fedora)
  dnf:
    name: "{{ item }}"
    state: present
  with_items: "{{ rpm_fusion_repos }}"
  when: ansible_distribution == 'Fedora'

- name: Install RPM Fusion Repos (CentOS)
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ rpm_fusion_repos }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
