---
# Variable configuration
- import_tasks: variables.yml

# Install Additional Repos
- import_tasks: additional_repos.yml
 
# Install multimedia applications and codecs
- name: Install multimedia applications
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ multimedia_application_packages }}"

- name: Install multimedia codecs
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ multimedia_codec_packages }}"
